# Specify version 2 (not 3) because ansible doesn't
# support version 3 so far
version: '2.4'

services:
  nginx:
    build:
      # Build an image using a Dockerfile from this dir. 
      context: ./containers/nginx/
    ports:
      # Redirect requests host:80->container:80
      - 80:80
    networks:
      # Connect our container to the custom network
      flask-app-net:
        # Assign ip address
        ipv4_address: 10.0.0.2
  flask:
    build:
      context: ./containers/flask/
    volumes:
      - ./containers/flask:/flask
    ports:
      # Expose port 9000 to inside containers' LAN
      - 9000
    networks:
      flask-app-net:
        ipv4_address: 10.0.0.3
  postgres:
    image: postgres:9.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test_db
    volumes:
      - ./containers/postgres:/var/lib/postgresql/data
    networks:
      flask-app-net:
        ipv4_address: 10.0.0.4

# Custom network description
networks:
  flask-app-net:
    ipam:
      config:
        - subnet: 10.0.0.0/16
          gateway: 10.0.0.1
        
