# Specify version 2 (not 3) because ansible doesn't
# support version 3 so far
version: '2.4'

services:
  nginx:
    build:
      # Build an image using a Dockerfile from this dir. 
      context: ./containers/nginx/
    ports:
      # Redirect requests host:80->container:80
      - 80:80
    networks:
      # Connect our container to the custom network
      flask-app-net:
        # Assign ip address
        ipv4_address: 10.0.0.2
  flask:
    build:
      context: ./containers/flask/
    volumes:
      - ./containers/flask:/flask
    ports:
      # Expose port 9000 to inside containers' LAN
      - 9000
    networks:
      flask-app-net:
        ipv4_address: 10.0.0.3
  postgres:
    # Take the image
    image: postgres:9.3
    # Redirect connection host:5432->container:5432
    ports:
      - "5432:5432"
    environment:
      # To create user
      - POSTGRES_USER=test
      # To make a password for external connections
      - POSTGRES_PASSWORD=test
      # To create a db
      - POSTGRES_DB=test_db
    volumes:
      # Mount host dir into container to store data persistently
      - ./containers/postgres/data:/var/lib/postgresql/data
    networks:
      flask-app-net:
        ipv4_address: 10.0.0.4

# Custom network description
networks:
  flask-app-net:
    ipam:
      config:
        - subnet: 10.0.0.0/16
          gateway: 10.0.0.1
        
